package com.blz.zhihudaily.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SPLASH_SCREEN_ENTITY".
 */
public class SplashScreenEntity {

    private String text;
    private String img;

    public SplashScreenEntity() {
    }

    public SplashScreenEntity(String text, String img) {
        this.text = text;
        this.img = img;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public String getImg() {
        return img;
    }

    public void setImg(String img) {
        this.img = img;
    }

}
