package com.blz.zhihudaily.entities;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "STORY_DETAIL_ENTITY".
 */
public class StoryDetailEntity {

    private String body;
    private String image_source;
    private String title;
    private String image;
    private String share_url;
    private String js;
    private String ga_prefix;
    private String section_thumbnail;
    private String type;
    private String id;
    private String css;

    public StoryDetailEntity() {
    }

    public StoryDetailEntity(String id) {
        this.id = id;
    }

    public StoryDetailEntity(String body, String image_source, String title, String image, String share_url, String js, String ga_prefix, String section_thumbnail, String type, String id, String css) {
        this.body = body;
        this.image_source = image_source;
        this.title = title;
        this.image = image;
        this.share_url = share_url;
        this.js = js;
        this.ga_prefix = ga_prefix;
        this.section_thumbnail = section_thumbnail;
        this.type = type;
        this.id = id;
        this.css = css;
    }

    public String getBody() {
        return body;
    }

    public void setBody(String body) {
        this.body = body;
    }

    public String getImage_source() {
        return image_source;
    }

    public void setImage_source(String image_source) {
        this.image_source = image_source;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getShare_url() {
        return share_url;
    }

    public void setShare_url(String share_url) {
        this.share_url = share_url;
    }

    public String getJs() {
        return js;
    }

    public void setJs(String js) {
        this.js = js;
    }

    public String getGa_prefix() {
        return ga_prefix;
    }

    public void setGa_prefix(String ga_prefix) {
        this.ga_prefix = ga_prefix;
    }

    public String getSection_thumbnail() {
        return section_thumbnail;
    }

    public void setSection_thumbnail(String section_thumbnail) {
        this.section_thumbnail = section_thumbnail;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getCss() {
        return css;
    }

    public void setCss(String css) {
        this.css = css;
    }

}
