package com.blz.zhihudaily.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.blz.zhihudaily.entities.StoryEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "STORY_ENTITY".
*/
public class StoryEntityDao extends AbstractDao<StoryEntity, String> {

    public static final String TABLENAME = "STORY_ENTITY";

    /**
     * Properties of entity StoryEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Image = new Property(0, String.class, "image", false, "IMAGE");
        public final static Property Type = new Property(1, String.class, "type", false, "TYPE");
        public final static Property Id = new Property(2, String.class, "id", true, "ID");
        public final static Property Ga_prefix = new Property(3, String.class, "ga_prefix", false, "GA_PREFIX");
        public final static Property Title = new Property(4, String.class, "title", false, "TITLE");
    };


    public StoryEntityDao(DaoConfig config) {
        super(config);
    }
    
    public StoryEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"STORY_ENTITY\" (" + //
                "\"IMAGE\" TEXT," + // 0: image
                "\"TYPE\" TEXT," + // 1: type
                "\"ID\" TEXT PRIMARY KEY NOT NULL ," + // 2: id
                "\"GA_PREFIX\" TEXT," + // 3: ga_prefix
                "\"TITLE\" TEXT);"); // 4: title
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"STORY_ENTITY\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, StoryEntity entity) {
        stmt.clearBindings();
 
        String image = entity.getImage();
        if (image != null) {
            stmt.bindString(1, image);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(2, type);
        }
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(3, id);
        }
 
        String ga_prefix = entity.getGa_prefix();
        if (ga_prefix != null) {
            stmt.bindString(4, ga_prefix);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(5, title);
        }
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2);
    }    

    /** @inheritdoc */
    @Override
    public StoryEntity readEntity(Cursor cursor, int offset) {
        StoryEntity entity = new StoryEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // image
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // type
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // id
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // ga_prefix
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // title
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, StoryEntity entity, int offset) {
        entity.setImage(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setType(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setGa_prefix(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setTitle(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(StoryEntity entity, long rowId) {
        return entity.getId();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(StoryEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
