package com.blz.zhihudaily.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.blz.zhihudaily.entities.StoryEntity;
import com.blz.zhihudaily.entities.StoryDetailEntity;
import com.blz.zhihudaily.entities.SplashScreenEntity;

import com.blz.zhihudaily.dao.StoryEntityDao;
import com.blz.zhihudaily.dao.StoryDetailEntityDao;
import com.blz.zhihudaily.dao.SplashScreenEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig storyEntityDaoConfig;
    private final DaoConfig storyDetailEntityDaoConfig;
    private final DaoConfig splashScreenEntityDaoConfig;

    private final StoryEntityDao storyEntityDao;
    private final StoryDetailEntityDao storyDetailEntityDao;
    private final SplashScreenEntityDao splashScreenEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        storyEntityDaoConfig = daoConfigMap.get(StoryEntityDao.class).clone();
        storyEntityDaoConfig.initIdentityScope(type);

        storyDetailEntityDaoConfig = daoConfigMap.get(StoryDetailEntityDao.class).clone();
        storyDetailEntityDaoConfig.initIdentityScope(type);

        splashScreenEntityDaoConfig = daoConfigMap.get(SplashScreenEntityDao.class).clone();
        splashScreenEntityDaoConfig.initIdentityScope(type);

        storyEntityDao = new StoryEntityDao(storyEntityDaoConfig, this);
        storyDetailEntityDao = new StoryDetailEntityDao(storyDetailEntityDaoConfig, this);
        splashScreenEntityDao = new SplashScreenEntityDao(splashScreenEntityDaoConfig, this);

        registerDao(StoryEntity.class, storyEntityDao);
        registerDao(StoryDetailEntity.class, storyDetailEntityDao);
        registerDao(SplashScreenEntity.class, splashScreenEntityDao);
    }
    
    public void clear() {
        storyEntityDaoConfig.getIdentityScope().clear();
        storyDetailEntityDaoConfig.getIdentityScope().clear();
        splashScreenEntityDaoConfig.getIdentityScope().clear();
    }

    public StoryEntityDao getStoryEntityDao() {
        return storyEntityDao;
    }

    public StoryDetailEntityDao getStoryDetailEntityDao() {
        return storyDetailEntityDao;
    }

    public SplashScreenEntityDao getSplashScreenEntityDao() {
        return splashScreenEntityDao;
    }

}
